name: Build & Deploy Emojar

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: emojar-frontend
      APP_DIR: /var/www/emojar
      NODE_VERSION: 20
      APP_PORT: "3006"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build

      - name: Verify standalone output
        run: |
          test -d .next/standalone || {
            echo "::error::'.next/standalone' not found. Set output: 'standalone' in next.config.mjs";
            exit 1;
          }

      - name: Package deploy bundle
        run: |
          set -euo pipefail
          mkdir -p deploy
          cp -r .next/standalone deploy/standalone
          cp -r .next/static deploy/static
          if [ -d public ]; then cp -r public deploy/public; fi

          # PM2 entry script
          cat > deploy/start.sh <<'EOS'
          #!/usr/bin/env bash
          set -euo pipefail
          cd "$(dirname "$0")/standalone"
          PORT=${PORT:-3006}
          node server.js
          EOS
          chmod +x deploy/start.sh

          tar -czf emojar.tar.gz -C deploy .

      - name: Upload artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          source: "emojar.tar.gz"
          target: "/tmp"

      - name: Deploy on EC2 (untar & restart PM2)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            set -euo pipefail

            APP_NAME="${APP_NAME:-emojar-frontend}"
            APP_DIR="${APP_DIR:-/var/www/emojar}"
            APP_PORT="${APP_PORT:-3006}"
            START_FILE="$APP_DIR/current/start.sh"

            # Prepare & unpack
            sudo mkdir -p "$APP_DIR"
            sudo chown -R "$USER:$USER" "$APP_DIR"
            rm -rf "$APP_DIR/current"
            mkdir -p "$APP_DIR/current"
            tar -xzf /tmp/emojar.tar.gz -C "$APP_DIR/current"

            # Start/restart with absolute path
            export PORT="$APP_PORT"
            if pm2 list | grep -q "$APP_NAME"; then
              pm2 restart "$APP_NAME" --update-env --time
            else
              pm2 start "$START_FILE" --name "$APP_NAME" --time
            fi

            pm2 save
            echo "Deployed $APP_NAME to $APP_DIR (port $APP_PORT)"
